create procedure ADD_GUIDE
@I_GUIDE_NUM char(4),
@I_FIRST_NAME char(15),
@I_LAST_NAME char(15)
AS
INSERT INTO GUIDE (GUIDE_NUM, LAST_NAME, FIRST_NAME)
VALUES (@I_GUIDE_NUM, @I_LAST_NAME, @I_FIRST_NAME);
