CREATE PROCEDURE InsertOrders
@I_ORDER_NUM char(5),
@I_ORDER_DATE date,
@I_CUSTOMER_NUM char(3)
AS
INSERT INTO ORDERS (ORDER_NUM, ORDER_DATE, CUSTOMER_NUM)
VALUES (@I_ORDER_NUM, @I_ORDER_DATE, @I_CUSTOMER_NUM);